# Generated by Django 3.1.4 on 2021-01-28 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type_of', models.CharField(choices=[('BA', 'Bank'), ('CC', 'Credit Card'), ('WA', 'Wallet')], default='WA', max_length=2)),
                ('initial_value', models.FloatField()),
                ('current_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(choices=[('TR', 'Transfer'), ('EX', 'Expense'), ('IM', 'Income')], max_length=2)),
                ('location', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=50)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('total_value', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40)),
                ('single_value', models.FloatField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transaction')),
            ],
        ),
    ]
